// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwrJgz1ZvBF4Z2Lu0vNuwZAHT1tV5WPsU',
    appId: '1:860136823856:web:f82be624c30051e91261f5',
    messagingSenderId: '860136823856',
    projectId: 'shopping-app-3bf0c',
    authDomain: 'shopping-app-3bf0c.firebaseapp.com',
    storageBucket: 'shopping-app-3bf0c.appspot.com',
    measurementId: 'G-2BC92YV765',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-oRtYuI3C0mDGhi2uytBSESUf57FoJs',
    appId: '1:860136823856:android:20b7efb433c218f51261f5',
    messagingSenderId: '860136823856',
    projectId: 'shopping-app-3bf0c',
    storageBucket: 'shopping-app-3bf0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZHXhokaCuHw0ND3wI8thWiadVdhJJdmw',
    appId: '1:860136823856:ios:549e03291ca3a2ca1261f5',
    messagingSenderId: '860136823856',
    projectId: 'shopping-app-3bf0c',
    storageBucket: 'shopping-app-3bf0c.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZHXhokaCuHw0ND3wI8thWiadVdhJJdmw',
    appId: '1:860136823856:ios:549e03291ca3a2ca1261f5',
    messagingSenderId: '860136823856',
    projectId: 'shopping-app-3bf0c',
    storageBucket: 'shopping-app-3bf0c.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwrJgz1ZvBF4Z2Lu0vNuwZAHT1tV5WPsU',
    appId: '1:860136823856:web:54f2150d22c394451261f5',
    messagingSenderId: '860136823856',
    projectId: 'shopping-app-3bf0c',
    authDomain: 'shopping-app-3bf0c.firebaseapp.com',
    storageBucket: 'shopping-app-3bf0c.appspot.com',
    measurementId: 'G-49S6MVXGQB',
  );

}